version: '3.7'

services:

  fleet_database:
    build: ./mysql_fleet_database
    container_name: fleet_database
    restart: always
    env_file:
    - ./.env
    volumes:
        - ./mysql_fleet_database/db_fleet_data:/var/lib/mysql
    ports:
        - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  data_gathering_service:
    build: ./data_gathering
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    container_name: data_gathering_service
    restart: always
    volumes:
      - ./data_gathering/:/app/
    ports:
      - 8001:8000
    env_file:
    - ./.env
    depends_on:
      fleet_database:
        condition: service_healthy

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - data_gathering_service